package cn.edu.xmu.JavaEE_Exp1.mapper.generator;

import cn.edu.xmu.JavaEE_Exp1.mapper.po.GoodsPo;
import cn.edu.xmu.JavaEE_Exp1.mapper.po.GoodsPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int insert(GoodsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int insertSelective(GoodsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    List<GoodsPo> selectByExample(GoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    GoodsPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") GoodsPo row, @Param("example") GoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") GoodsPo row, @Param("example") GoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsPo row);
}